### ISSUE TITLE
Toevoegen Depicts-tags aan afbeeldingen AAJH-bijdragers

### ISSUE THREAD

**Issue by MirjamC** [KBNLresearch/Hackalod#2]
Toevoegen Depicts-tags aan afbeeldingen AAJH-bijdragers

**Comment by ookgezellig** [comment]
Voor alle Commons-images in de tabel https://w.wiki/F4$ zijn P180-Depicts tags toegevoegd aan de structured data.

Bijvoorbeeld: 
* https://commons.wikimedia.org/wiki/File:Abdias%20Widmar%20(cropped).jpg
* Deze URL is equivalent met https://commons.wikimedia.org/wiki/Special:EntityData/M54507096
* From that Mnumber (M54507096) we can request the (Wikidata Qnumbers of the) depicted person via the API call https://commons.wikimedia.org/w/api.php?action=wbgetentities&format=json&ids=M54507096 as JSON:

![afbeelding](https://user-images.githubusercontent.com/6546244/138128947-0cb3367e-9596-460d-a509-fec11799cf6b.png)
