### ISSUE TITLE
AAJH: toevoegen van de namen van de bijdragers aan de items over de bijdragen

### ISSUE THREAD

**Issue by MirjamC** [KBNLresearch/Hackalod#3]
OJ: AAJH: toevoegen van de namen van de bijdragers aan de items over de bijdragen (zie bv https://www.wikidata.org/wiki/Q105528355)

**Comment by ookgezellig** [comment]
Gedaan, via P170 (Creator) , zie bv https://www.wikidata.org/wiki/Q105528368

SPARQL-query ter controle:  https://w.wiki/4FV5
